//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTechnology
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NewTechnologyEntities : DbContext
    {
        public NewTechnologyEntities()
            : base("name=NewTechnologyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ЕдИзм> ЕдИзм { get; set; }
        public virtual DbSet<Материалы> Материалы { get; set; }
        public virtual DbSet<Партнеры> Партнеры { get; set; }
        public virtual DbSet<Поставщики> Поставщики { get; set; }
        public virtual DbSet<Продукция> Продукция { get; set; }
        public virtual DbSet<СоставЗаявки> СоставЗаявки { get; set; }
        public virtual DbSet<Сотрудники> Сотрудники { get; set; }
        public virtual DbSet<ТипМатериалов> ТипМатериалов { get; set; }
        public virtual DbSet<ТипПартнеров> ТипПартнеров { get; set; }
        public virtual DbSet<ТипПродукции> ТипПродукции { get; set; }
        public virtual DbSet<Заявка> Заявка { get; set; }
    }
}
