//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTechnology
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заявка
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заявка()
        {
            this.СоставЗаявки = new HashSet<СоставЗаявки>();
        }
    
        public int Код { get; set; }
        public Nullable<int> КодПродукции { get; set; }
        public Nullable<int> КодПартнера { get; set; }
        public Nullable<int> КоличествоПродукции { get; set; }
        public Nullable<System.DateTime> ДатаЗаявки { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СоставЗаявки> СоставЗаявки { get; set; }
        public virtual Партнеры Партнеры { get; set; }
        public virtual Продукция Продукция { get; set; }
    }
}
