//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTechnology
{
    using System;
    using System.Collections.Generic;
    
    public partial class Материалы
    {
        public int Код { get; set; }
        public Nullable<int> КодТипМатериалов { get; set; }
        public Nullable<int> КодПоставщика { get; set; }
        public Nullable<int> КолвоВУпаковке { get; set; }
        public Nullable<int> КодЕдИзм { get; set; }
        public string Описание { get; set; }
        public string Изображение { get; set; }
        public Nullable<double> Стоимость { get; set; }
        public Nullable<int> КолвоНаСкладе { get; set; }
        public Nullable<int> МинКолво { get; set; }
    
        public virtual ЕдИзм ЕдИзм { get; set; }
        public virtual Поставщики Поставщики { get; set; }
        public virtual ТипМатериалов ТипМатериалов { get; set; }
    }
}
