//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTechnology
{
    using System;
    using System.Collections.Generic;
    
    public partial class Партнеры
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Партнеры()
        {
            this.Заявка = new HashSet<Заявка>();
        }
    
        public int Код { get; set; }
        public Nullable<int> КодТипПартнера { get; set; }
        public string Наименование { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public string Почта { get; set; }
        public string Телефон { get; set; }
        public string ЮрАдрес { get; set; }
        public string ИНН { get; set; }
        public Nullable<int> Рейтинг { get; set; }
        public string Логотип { get; set; }
        public string МестаПродаж { get; set; }
    
        public virtual ТипПартнеров ТипПартнеров { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заявка> Заявка { get; set; }
    }
}
