//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTechnology
{
    using System;
    using System.Collections.Generic;
    
    public partial class Продукция
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Продукция()
        {
            this.Заявка = new HashSet<Заявка>();
        }
    
        public int Код { get; set; }
        public Nullable<int> КодТипПродукции { get; set; }
        public string Наименование { get; set; }
        public Nullable<int> Артикул { get; set; }
        public Nullable<double> МинСтоимость { get; set; }
        public string Описание { get; set; }
        public string Изображение { get; set; }
        public Nullable<double> Ширина { get; set; }
        public Nullable<double> Длина { get; set; }
        public Nullable<double> Высота { get; set; }
        public Nullable<double> ВесБезУпаковки { get; set; }
        public Nullable<double> ВесСУпаковкой { get; set; }
        public string СертификатКачества { get; set; }
        public Nullable<int> НомерСтандарта { get; set; }
        public Nullable<System.TimeSpan> ВремяИзготовления { get; set; }
        public Nullable<double> Себестоимость { get; set; }
        public Nullable<int> НомерЦеха { get; set; }
        public Nullable<int> КолвоЧелНаПроизводстве { get; set; }
    
        public virtual ТипПродукции ТипПродукции { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заявка> Заявка { get; set; }
    }
}
