//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTechnology
{
    using System;
    using System.Collections.Generic;
    
    public partial class СоставЗаявки
    {
        public int Код { get; set; }
        public Nullable<int> КодЗаявки { get; set; }
        public Nullable<double> Стоимость { get; set; }
    
        public virtual Заявка Заявка { get; set; }
    }
}
